# Generated by Django 4.1.4 on 2022-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='Country',
            field=models.CharField(default='Jordan', max_length=255),
        ),
    ]
